author: RABE_IT Services
author_url: https://berndrabe.de
github_url: https://github.com/HHuckebein/Base64.git
copyright: '© 2016 [RABE_IT Services](https://berndrabe.de) under [open source license](https://github.com/HHuckebein/Base64/blob/master/LICENSE.txt).'
clean: true

swift_version: 4.0.3
